function aff = circlefit(circle_x, circle_y)
%CREATEFIT(CIRCLE_X,CIRCLE_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : circle_x
%      Y Output: circle_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Apr-2022 02:17:00


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( circle_x, circle_y );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, ~] = fit( xData, yData, ft );
coeff = coeffvalues(fitresult);
% Plot fit with data.
% monitor = figure( 'Name', 'Contact Angle fitting' );
% h = plot( fitresult, xData, yData );
% legend( h, 'circle_y vs. circle_x', 'fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'circle_x', 'Interpreter', 'none' );
% ylabel( 'circle_y', 'Interpreter', 'none' );
% grid on
% pause(0.5)
% close(monitor)

temp_x = -coeff(2)+sqrt((coeff(2))^2-4*coeff(1)*coeff(3))/(2*coeff(1));
slope = 2*coeff(1)*temp_x+coeff(2);
aff = cos(atan(abs(slope)));

